defaultType: browser
name: Google Search
steps:
  - action: visit
    name: visit google
    options:
      url: https://google.com
  - action: input
    name: search
    inputs:
      - name: input search params
        element:
          identifier: 'input[name="q"]'
        action: input
        value: "we're searching"
      - name: submit
        element:
          identifier: 'input[value="Google Search"]'
        action: click